//! Cross-binary parity test: drive the Rust port's
//! `crate::transaction::create_unsigned_transaction` with the same
//! logical inputs the Go fixturegen used and assert the serialized
//! `PartiallySignedTransaction` bytes are byte-equal.
//!
//! Fixture: `tests/fixtures/coinsel_create_unsigned.json`,
//! generated by `tests/fixtures/coinsel_fixturegen.go.txt` running
//! against `kaspad@4bb5bf25d3f2279ec2a61c3b4f7bb083b5f522b2`'s
//! `libkaspawallet.CreateUnsignedTransaction` +
//! `serialization.SerializePartiallySignedTransaction`.
//!
//! This is the cross-binary wire-compat gate at the unsigned-PST
//! emission layer: if `coinsel::select_utxos` produces the same
//! ordering as Go (proven separately by the algorithmic unit tests
//! in `coinsel::tests`) AND `transaction::create_unsigned_transaction`
//! produces byte-identical PST bytes for the same inputs, then the
//! Rust send / sweep / create-unsigned-transaction paths emit the
//! same unsigned-transaction bytes the Go binary does for any
//! logical input set.

use kaspa_addresses::{Address, Prefix as AddrPrefix};
use kaspa_consensus_core::config::params::Params;
use kaspa_consensus_core::network::NetworkType;
use kaspa_consensus_core::tx::{ScriptPublicKey, UtxoEntry};
use kaspawallet::coinsel::{Selection, WalletConfig, select_utxos};
use kaspawallet::serialization::serialize_partially_signed_transaction;
use kaspawallet::transaction::{Payment, Utxo, create_unsigned_transaction, outpoint};
use serde::Deserialize;

#[derive(Deserialize)]
struct UtxoFixture {
    transaction_id: String,
    index: u32,
    amount: u64,
    script_public_key_version: u32,
    script_public_key_hex: String,
    block_daa_score: u64,
    is_coinbase: bool,
    derivation_path: String,
}

#[derive(Deserialize)]
struct PaymentFixture {
    address: String,
    amount: u64,
}

#[derive(Deserialize)]
struct Fixture {
    extended_public_keys: Vec<String>,
    minimum_signatures: u32,
    selected_utxos: Vec<UtxoFixture>,
    payments: Vec<PaymentFixture>,
    expected_pst_hex: String,
}

fn load_fixture() -> Fixture {
    let mut path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("tests");
    path.push("fixtures");
    path.push("coinsel_create_unsigned.json");
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("parse coinsel_create_unsigned.json")
}

fn parse_outpoint(hex_id: &str, index: u32) -> kaspawallet::serialization::wire::Outpoint {
    let bytes = hex::decode(hex_id).expect("transaction_id hex");
    let mut arr = [0u8; 32];
    assert_eq!(bytes.len(), arr.len(), "transaction_id must be 32 bytes");
    arr.copy_from_slice(&bytes);
    outpoint(arr, index)
}

fn parse_utxo(f: &UtxoFixture) -> Utxo {
    let script_bytes = hex::decode(&f.script_public_key_hex).expect("script hex");
    let version = u16::try_from(f.script_public_key_version).expect("script version fits u16");
    let spk = ScriptPublicKey::new(version, script_bytes.into());
    Utxo {
        outpoint: parse_outpoint(&f.transaction_id, f.index),
        utxo_entry: UtxoEntry {
            amount: f.amount,
            script_public_key: spk,
            block_daa_score: f.block_daa_score,
            is_coinbase: f.is_coinbase,
        },
        derivation_path: f.derivation_path.clone(),
    }
}

fn parse_payment(f: &PaymentFixture) -> Payment {
    let address = Address::try_from(f.address.as_str()).unwrap_or_else(|e| panic!("decode address {}: {e:?}", f.address));
    Payment { address, amount: f.amount }
}

#[test]
fn test_select_utxos_picks_largest_first_against_go_input_set() {
    // Drive `select_utxos` over the same sorted-desc UTXO list the
    // Go fixturegen prepared and assert that the selection it returns
    // begins with the largest UTXO. The Go fixturegen does NOT call
    // selectUTXOs (it calls libkaspawallet.CreateUnsignedTransaction
    // directly with a pre-baked selected_utxos slice); this test
    // confirms the Rust selector consuming the SAME logical UTXO
    // set produces the same head-of-list ordering Go's selectUTXOs
    // would.
    let fixture = load_fixture();
    let utxos: Vec<Utxo> = fixture.selected_utxos.iter().map(parse_utxo).collect();

    let cfg = WalletConfig {
        extended_public_keys: fixture.extended_public_keys.clone(),
        minimum_signatures: fixture.minimum_signatures,
        address_prefix: AddrPrefix::Testnet,
        ecdsa: false,
    };
    let params = Params::from(NetworkType::Testnet);

    // The fixture's three UTXOs sum to 1600 KAS (1000 + 500 + 100 KAS,
    // expressed in sompi). Spend 50 KAS so the loop must take more
    // than one input to clear the KIP-9 dust margin (Go break case 2
    // requires `selected.len() > 1`), exercising the head-of-list
    // ordering rule.
    let spend = 5_000_000_000;
    let Selection { selected, .. } = select_utxos(&cfg, &params, &utxos, &[], spend, false, 1.0, 1_000_000_000).expect("select_utxos");

    assert!(!selected.is_empty(), "selection must be non-empty for a feasible spend");
    assert_eq!(
        selected[0].utxo_entry.amount, utxos[0].utxo_entry.amount,
        "first selected UTXO must be the largest (sorted-desc input -> head-of-list output)"
    );
}

#[test]
fn test_create_unsigned_transaction_byte_identical_to_go_fixture() {
    let fixture = load_fixture();
    let utxos: Vec<Utxo> = fixture.selected_utxos.iter().map(parse_utxo).collect();
    let payments: Vec<Payment> = fixture.payments.iter().map(parse_payment).collect();

    let pst = create_unsigned_transaction(&fixture.extended_public_keys, fixture.minimum_signatures, &payments, &utxos)
        .expect("create_unsigned_transaction");
    let bytes = serialize_partially_signed_transaction(&pst).expect("serialize");
    let actual_hex = hex::encode(&bytes);

    assert_eq!(
        actual_hex,
        fixture.expected_pst_hex,
        "Rust create_unsigned_transaction PST bytes must match Go libkaspawallet.CreateUnsignedTransaction byte-for-byte\n\
         expected ({} bytes): {}\n\
         actual   ({} bytes): {}",
        fixture.expected_pst_hex.len() / 2,
        fixture.expected_pst_hex,
        bytes.len(),
        actual_hex
    );
}
