//! Wire format for unsigned and partially-signed transactions.
//!
//! Mirrors the Go reference at
//! `https://github.com/kaspanet/kaspad/blob/master/cmd/kaspawallet/libkaspawallet/serialization/serialization.go`
//! plus the proto schema at
//! `https://github.com/kaspanet/kaspad/blob/master/cmd/kaspawallet/libkaspawallet/serialization/protoserialization/wallet.proto`
//! (vendored verbatim into `cmd/kaspawallet/proto/wallet.proto`).
//!
//! The on-disk / on-wire format is protobuf-3. The Rust types are
//! generated by `prost-build` from the vendored proto file (see
//! `build.rs`). Proto3's canonical encoding is deterministic for
//! the same logical message, so the Go binary's
//! `proto.Marshal(...)` output and this crate's
//! `prost::Message::encode_to_vec(...)` output for the same
//! `PartiallySignedTransaction` content are byte-equal modulo
//! proto3 encoder-implementation details that both languages
//! handle the same way (tag-order, default-value omission, varint
//! encoding). Cross-binary byte-equality is the verifying gate of
//! the cross-binary parity tests scheduled for the
//! validation-harness batch; the in-tree tests here prove
//! encode/decode round-trip and the structural shape of the wire
//! messages.

mod codec;
mod error;

#[cfg(test)]
mod tests;

/// Auto-generated prost types from `proto/wallet.proto`. Re-exported
/// under `wire::*` so consumers can refer to the types without
/// depending on the build-script output directory.
pub mod wire {
    #![allow(clippy::pedantic, clippy::nursery, missing_docs)]
    include!(concat!(env!("OUT_DIR"), "/protoserialization.rs"));
}

pub use codec::{
    deserialize_domain_transaction, deserialize_partially_signed_transaction, serialize_domain_transaction,
    serialize_partially_signed_transaction,
};
pub use error::SerializationError;
