//! Wire format for unsigned and partially-signed transactions.
//!
//! The on-disk / on-wire format is protobuf-3, with the schema
//! vendored at `cmd/kaspawallet/proto/wallet.proto`. The Rust
//! types are generated by `prost-build` (see `build.rs`).
//!
//! Proto3's canonical encoding is deterministic for the same
//! logical message; the encode/decode round-trip and structural
//! shape are exercised by the in-tree tests, and cross-
//! implementation byte-equality is the gate exercised by the
//! parity tests.

mod codec;
mod error;

#[cfg(test)]
mod tests;

/// Auto-generated prost types from `proto/wallet.proto`. Re-exported
/// under `wire::*` so consumers can refer to the types without
/// depending on the build-script output directory.
pub mod wire {
    #![allow(clippy::pedantic, clippy::nursery, missing_docs)]
    include!(concat!(env!("OUT_DIR"), "/protoserialization.rs"));
}

pub use codec::{
    deserialize_domain_transaction, deserialize_partially_signed_transaction, serialize_domain_transaction,
    serialize_partially_signed_transaction,
};
pub use error::SerializationError;
